---
- name: Install Zabbix User sudoers.d file
  hosts: all
  become: true
  gather_facts: false

  tasks:
    - name: Copy over file
      ansible.builtin.copy:
        src: ../files/zabbix_sudoers
        dest: /etc/sudoers.d/zabbix
        owner: root
        group: root
        mode: 0400

    - name: Install smartmontools if it's not already installed
      ansible.builtin.apt:
        update_cache: true
        name: smartmontools
        state: present
      when: ansible_pkg_mgr == "apt"

    - name: Install smartmontools if it's not already installed
      ansible.builtin.dnf:
        update_cache: true
        name: smartmontools
        state: present
      when: ansible_pkg_mgr == "cnf"

    - name: restart zabbix agent 2
      ansible.builtin.systemd:
        state: restarted
        name: zabbix-agent2
