---
- name: Install Zabbix User sudoers.d file
  hosts: all
  become: true
  gather_facts: false

  tasks:
    - name: Copy over file
      ansible.builtin.copy:
        src: ../files/zabbix_sudoers
        dest: /etc/sudoers.d/zabbix
        owner: root
        group: root
        mode: 0400

    - name: restart zabbix agent 2
      ansible.builtin.systemd:
        state: restarted
        daemon_reload: true
        name: zabbix-agent2
