- name: Install package
  hosts: all
  gather_facts: true
  become: true
  vars_prompt:

    - name: package
      prompt: "What package do you want to install?"
      private: false

  tasks:
    - name: Install on Debian and variants - {{ package }}
      ansible.builtin.apt:
        name: '{{ package }}'
      when: ansible_pkg_mgr == "apt"

    - name: Install on RedHat and variants - {{ package }}
      ansible.builtin.dnf:
        name: '{{ package }}'
      when: ansible_pkg_mgr == "dnf"