- name: Install package
  hosts: all
  gather_facts: false
  become: true
  vars_prompt:

    - name: package
      prompt: "What package do you want to install?"
      private: false

  tasks:
    - name: Install the package {{ package }} on Debian and Variants
      ansible.builtin.apt:
        name: '{{ package }}'
      when: ansible_pkg_mgr == "apt"

    - name: Install the package {{ package }} on RedHat and Variants
      ansible.builtin.apt:
        name: '{{ package }}'
      when: ansible_pkg_mgr == "dnf"
